---
- name: Check Polkadot Version
  hosts: polkadot_nodes
  gather_facts: false
  tasks:
    - name: Check if Polkadot is installed
      command: "polkadot --version"
      ignore_errors: true
      register: polkadot_version_result

    - name: Extract Polkadot version
      set_fact:
        polkadot_version: "{{ polkadot_version_result.stdout_lines[0] | regex_replace('^.* ([0-9]+\\.[0-9]+\\.[0-9]+).*$', '\\1') }}"
      when: polkadot_version_result.rc == 0

    - name: Save Polkadot version to version.yml
      copy:
        content: |
          polkadot_version: "{{ polkadot_version }}"
        dest: version.yaml
      when: polkadot_version_result.rc == 0
