---
- name: Deploy Polkadot Full Node
  hosts: polkadot_nodes
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: true

  tasks:
    - name: Ansible task
      debug:
        msg: "Running Ansible task on host {{ inventory_hostname }}"

    - name: Update package cache and install dependencies
      apt:
        update_cache: yes
        force_apt_get: yes
        name: "{{ item }}"
      loop:
        - unzip
        - wget

    - name: Create Polkadot user
      user:
        name: polkadot
        comment: "Polkadot Node User"
        system: true
        shell: /bin/bash

    - name: Create Polkadot data directory
      file:
        path: /var/lib/polkadot
        state: directory
        owner: polkadot
        group: polkadot

    - name: Download and extract Polkadot binary
      shell: "wget https://github.com/paritytech/polkadot/releases/download/v1.0.0/polkadot -O /usr/local/bin/polkadot && chmod +x /usr/local/bin/polkadot"
      args:
        creates: /usr/local/bin/polkadot

    - name: Download and extract Polkadot update binary
      shell: "wget https://github.com/paritytech/polkadot-sdk/archive/refs/tags/v1.5.0-rc4.zip -O /tmp/polkadot-update.zip && unzip /tmp/polkadot-update.zip -d /tmp/ && mv /tmp/polkadot-sdk-1.5.0-rc4/polkadot /usr/local/bin/ && chmod +x /usr/local/bin/polkadot"
  
    - name: Start Polkadot
      command: "/usr/local/bin/polkadot --name 'polkadot-node{{ inventory_hostname }}' --validator"
      async: 0  
      poll: 0 

    - name: Configure Polkadot service
      template:
        src: polkadot.service.j2
        dest: /etc/systemd/system/polkadot.service
      notify: Reload Polkadot Service

    - name: Start and enable Polkadot service
      systemd:
        name: polkadot
        state: started
        enabled: yes

  handlers:
    - name: Reload Polkadot Service
      systemd:
        name: polkadot
        state: reloaded
