---
- name: Deploy Polkadot Full Node   # this Ansible playbook installs polkadot prebuilt binaries for a full node deployment
  hosts: polkadot_nodes
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: true

  vars:
    latest_version: "1.2.0"     # please use this to specify the latest Polkadot SDK version

  tasks:  

    - name: Ansible task
      debug:
        msg: "Running Ansible task on host {{ inventory_hostname }}"   

    - name: Confirm Polkadot is installed
      command: "polkadot --version"
      ignore_errors: true
      register: polkadot_version_result
    
    - name: Extract Polkadot version
      set_fact:
        polkadot_version: "{{ polkadot_version_result.stdout_lines[0] | regex_replace('^.* ([0-9]+\\.[0-9]+\\.[0-9]+).*$', '\\1') }}"
      when: polkadot_version_result.rc == 0

    - name: Display Polkadot Version    # display current version
      debug:
        msg: "Current Polkadot version is {{ polkadot_version }}"
      when: polkadot_version is defined

    - name: Notify if Polkadot Not Installed    # notify in case polkadot is not installed
      debug:
        msg: "Polkadot is currently not installed. Installing v1.0.0 and then running update to the latest."
      when: polkadot_version is not defined

    - name: Create Polkadot user    # create polkadot user for service
      user:
        name: polkadot
        comment: "Polkadot Node User"
        system: true
        shell: /bin/bash

    - name: Create Polkadot data directory     # create polkadot directory
      file:
        path: /var/lib/polkadot
        state: directory
        owner: polkadot
        group: polkadot

    - name: Download and extract v1.0.0 Polkadot binary     # if no version is found previously then install v1.0.0
      get_url:
        url: "https://github.com/paritytech/polkadot/releases/download/v1.0.0/polkadot"
        dest: "/usr/local/bin/polkadot"
        mode: '0755'
      when: 
        - polkadot_version is not defined

    - name: Confirm new Polkadot version
      command: "polkadot --version"
      ignore_errors: true
      register: polkadot_version_result

    - name: Extract new Polkadot version
      set_fact:
        polkadot_version: "{{ polkadot_version_result.stdout_lines[0] | regex_replace('^.* ([0-9]+\\.[0-9]+\\.[0-9]+).*$', '\\1') }}"
      when: polkadot_version_result.rc == 0

    - name: Download and extract Polkadot update binary 1     # if a version of the 'polkadot' binary is found, compare this to the latest version (specified above), and install the latest version if needed
      ansible.builtin.get_url:
        url: "https://github.com/paritytech/polkadot-sdk/releases/download/polkadot-v{{ latest_version }}/polkadot"
        dest: "/usr/local/bin/polkadot"
        mode: '0755'
      when: 
        - polkadot_version == "1.0.0"

    - name: Confirm new Polkadot version
      command: "polkadot --version"
      ignore_errors: true
      register: polkadot_version_result

    - name: Extract new Polkadot version
      set_fact:
        polkadot_version: "{{ polkadot_version_result.stdout_lines[0] | regex_replace('^.* ([0-9]+\\.[0-9]+\\.[0-9]+).*$', '\\1') }}"
      when: polkadot_version_result.rc == 0

    - name: Download and extract Polkadot update binary 2     # if a version of the 'polkadot execute worker' binary is found, compare this to the latest version (specified above), and install the latest version if needed
      ansible.builtin.get_url:
        url: "https://github.com/paritytech/polkadot-sdk/releases/download/polkadot-v{{ latest_version }}/polkadot-execute-worker"
        dest: "/usr/local/bin/polkadot-execute-worker"
        mode: '0755'
      when: 
        - polkadot_version == "1.0.0"    # Seems that after first update binary install, the version still reflect as v1.0.0

    - name: Download and extract Polkadot update binary 3     # if a version of the 'polkadot prepare worker' binary is found, compare this to the latest version (specified above), and install the latest version if needed
      ansible.builtin.get_url:
        url: "https://github.com/paritytech/polkadot-sdk/releases/download/polkadot-v{{ latest_version }}/polkadot-prepare-worker"
        dest: "/usr/local/bin/polkadot-prepare-worker"
        mode: '0755'
      when: 
        - polkadot_version == "1.0.0"  

    - name: Configure Polkadot service      # parameters in the polkadot.service.j2 file configure systemd to manage the polkadot service
      template:
        src: polkadot.service.j2
        dest: /etc/systemd/system/polkadot.service

    - name: Start and enable Polkadot service     #  start the service using systemd
      systemd:
        name: polkadot
        state: started
        enabled: yes

    - name: Extract Final Polkadot version
      set_fact:
        polkadot_version: "{{ polkadot_version_result.stdout_lines[0] | regex_replace('^.* ([0-9]+\\.[0-9]+\\.[0-9]+).*$', '\\1') }}"
      when: polkadot_version_result.rc == 0

    - name: Console Final Polkadot Version
      debug:
        msg: "Final Polkadot version is {{ polkadot_version }}"